### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by vikash0837** [sharmaeklavya2/notes-source#1]
Building src/cmo/08-coordinate-descent.tex
Command '['pdflatex', '-interaction=batchmode', '-output-directory=output/cmo', 'src/cmo/08-coordinate-descent.tex']' returned non-zero exit status 1.
src/cmo/08-coordinate-descent.tex failed

**Comment by sharmaeklavya2** [comment]
Thanks for reporting this issue! I found the bug and fixed it.
